#!/usr/bin/env python3
"""
PyInstaller Build Script for Rong-E agent
========================================

This script builds the Rong-E agent into a standalone executable.

Usage:
    python build_agent.py [--onefile] [--debug]

Options:
    --onefile   Create a single executable file (slower startup, easier distribution)
    --debug     Include debug symbols and console output

Requirements:
    pip install pyinstaller

Output:
    dist/ronge_agent (or dist/ronge_agent.exe on Windows)
"""

import os
import sys
import shutil
import subprocess
from pathlib import Path

# Project paths
SCRIPT_DIR = Path(__file__).parent.absolute()
PROJECT_ROOT = SCRIPT_DIR  # agent/ folder
DIST_DIR = PROJECT_ROOT / "dist"
BUILD_DIR = PROJECT_ROOT / "build"
SPEC_FILE = PROJECT_ROOT / "ronge_agent.spec"

# Entry point
ENTRY_POINT = PROJECT_ROOT / "server.py"

# Data files to include
DATA_FILES = [
    # (source, destination_folder)
    ("prompts", "prompts"),  # System prompts
    ("config", "config"),    # Configuration files (excluding secrets)
]

# Hidden imports that PyInstaller might miss
HIDDEN_IMPORTS = [
    # FastAPI and dependencies
    "fastapi",
    "uvicorn",
    "uvicorn.logging",
    "uvicorn.loops",
    "uvicorn.loops.auto",
    "uvicorn.protocols",
    "uvicorn.protocols.http",
    "uvicorn.protocols.http.auto",
    "uvicorn.protocols.websockets",
    "uvicorn.protocols.websockets.auto",
    "uvicorn.lifespan",
    "uvicorn.lifespan.on",
    "starlette",
    "starlette.routing",
    "starlette.middleware",
    "starlette.middleware.cors",
    "anyio",
    "anyio._backends",
    "anyio._backends._asyncio",

    # LangChain
    "langchain",
    "langchain_core",
    "langchain_google_genai",
    "langchain.agents",
    "langchain.tools",
    "langchain.memory",
    "langchain.prompts",
    "langchain.schema",

    # Google APIs
    "google.oauth2",
    "google.oauth2.credentials",
    "google.auth",
    "google.auth.transport",
    "google.auth.transport.requests",
    "googleapiclient",
    "googleapiclient.discovery",

    # Other dependencies
    "pydantic",
    "pydantic_core",
    "httpx",
    "httpcore",
    "h11",
    "websockets",
    "certifi",
    "charset_normalizer",
    "idna",
    "sniffio",

    # MCP (Model Context Protocol)
    "mcp",

    # Embeddings and vector store
    "chromadb",
    "sentence_transformers",

    # Agent modules
    "agent",
    "agent.agents",
    "agent.agents.agent",
    "agent.agents.google_agent",
    "agent.tools",
    "agent.services",
    "agent.services.google_service",
    "agent.services.rag",
    "agent.models",
    "agent.models.mcp_config"
]

# Packages to exclude (reduce size)
EXCLUDES = [
    "tkinter",
    "matplotlib",
    "numpy.tests",
    "scipy",
    "cv2",
    "torch",  # If not needed
    "tensorflow",
    "keras",
]


def clean_build():
    """Remove previous build artifacts."""
    print("🧹 Cleaning previous builds...")
    for path in [DIST_DIR, BUILD_DIR]:
        if path.exists():
            shutil.rmtree(path)
            print(f"   Removed: {path}")


def generate_spec_file(onefile: bool = False, debug: bool = False):
    """Generate PyInstaller spec file."""
    print("📝 Generating spec file...")

    # Build data files list
    datas_list = []
    for src, dest in DATA_FILES:
        src_path = PROJECT_ROOT / src
        if src_path.exists():
            datas_list.append(f"('{src_path}', '{dest}')")

    datas_str = ",\n        ".join(datas_list) if datas_list else ""

    # Build hidden imports list
    hidden_str = ",\n        ".join(f"'{h}'" for h in HIDDEN_IMPORTS)

    # Build excludes list
    excludes_str = ",\n        ".join(f"'{e}'" for e in EXCLUDES)

    spec_content = f'''# -*- mode: python ; coding: utf-8 -*-
"""
Rong-E agent PyInstaller Spec File
Generated by build_agent.py
"""

block_cipher = None

a = Analysis(
    ['{ENTRY_POINT}'],
    pathex=['{PROJECT_ROOT}'],
    binaries=[],
    datas=[
        {datas_str}
    ],
    hiddenimports=[
        {hidden_str}
    ],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[
        {excludes_str}
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

'''

    if onefile:
        spec_content += f'''
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='ronge_agent',
    debug={debug},
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console={debug},  # Show console in debug mode
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
'''
    else:
        spec_content += f'''
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='ronge_agent',
    debug={debug},
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console={debug},
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='ronge_agent',
)
'''

    with open(SPEC_FILE, 'w') as f:
        f.write(spec_content)

    print(f"   Created: {SPEC_FILE}")


def run_pyinstaller():
    """Run PyInstaller with the generated spec file."""
    print("🔨 Running PyInstaller...")

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--clean",
        "--noconfirm",
        str(SPEC_FILE)
    ]

    result = subprocess.run(cmd, cwd=PROJECT_ROOT)

    if result.returncode != 0:
        print("❌ PyInstaller failed!")
        sys.exit(1)

    print("✅ Build complete!")


def create_launcher_script():
    """Create a launcher script for the built executable."""
    print("📜 Creating launcher script...")

    launcher_path = DIST_DIR / "run_ronge_agent.sh"

    launcher_content = '''#!/bin/bash
# Rong-E agent Launcher
# This script runs the Rong-E agent server

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Set environment variables if needed
export PYTHONUNBUFFERED=1

# Run the agent
if [ -f "$SCRIPT_DIR/ronge_agent/ronge_agent" ]; then
    # Directory mode
    exec "$SCRIPT_DIR/ronge_agent/ronge_agent" "$@"
elif [ -f "$SCRIPT_DIR/ronge_agent" ]; then
    # Single file mode
    exec "$SCRIPT_DIR/ronge_agent" "$@"
else
    echo "Error: ronge_agent executable not found!"
    exit 1
fi
'''

    with open(launcher_path, 'w') as f:
        f.write(launcher_content)

    os.chmod(launcher_path, 0o755)
    print(f"   Created: {launcher_path}")


def print_summary():
    """Print build summary and usage instructions."""
    print("\n" + "=" * 60)
    print("BUILD SUMMARY")
    print("=" * 60)

    # Find the executable
    exe_path = None
    if (DIST_DIR / "ronge_agent" / "ronge_agent").exists():
        exe_path = DIST_DIR / "ronge_agent" / "ronge_agent"
    elif (DIST_DIR / "ronge_agent").exists():
        exe_path = DIST_DIR / "ronge_agent"

    if exe_path:
        size_mb = exe_path.stat().st_size / (1024 * 1024)
        print(f"✅ Executable: {exe_path}")
        print(f"   Size: {size_mb:.1f} MB")

    print("\n📖 Usage:")
    print("   ./dist/run_ronge_agent.sh")
    print("   OR")
    print("   ./dist/ronge_agent/ronge_agent")

    print("\n🔗 The server will run on:")
    print("   http://localhost:8000")
    print("   WebSocket: ws://localhost:8000/ws")

    print("\n⚠️  Note: Make sure to copy your config files:")
    print("   - config/credentials.json (Google OAuth)")
    print("   - config/token.json (if exists)")
    print("=" * 60)


def main():
    import argparse

    parser = argparse.ArgumentParser(description="Build Rong-E agent executable")
    parser.add_argument("--onefile", action="store_true",
                        help="Create single executable file")
    parser.add_argument("--debug", action="store_true",
                        help="Include debug symbols and console")
    parser.add_argument("--clean-only", action="store_true",
                        help="Only clean build artifacts")
    args = parser.parse_args()

    print("🚀 Rong-E agent Build Script")
    print("=" * 60)

    # Change to project directory
    os.chdir(PROJECT_ROOT)

    # Clean previous builds
    clean_build()

    if args.clean_only:
        print("✅ Clean complete!")
        return

    # Generate spec file
    generate_spec_file(onefile=args.onefile, debug=args.debug)

    # Run PyInstaller
    run_pyinstaller()

    # Create launcher
    create_launcher_script()

    # Print summary
    print_summary()


if __name__ == "__main__":
    main()
