# -*- mode: python ; coding: utf-8 -*-
"""
Rong-E Agent PyInstaller Spec File
Generated by build_agent.py
"""

block_cipher = None

a = Analysis(
    ['/Users/hojinsohn/Rong-E/agent/server.py'],
    pathex=['/Users/hojinsohn/Rong-E/agent'],
    binaries=[],
    datas=[
        ('/Users/hojinsohn/Rong-E/agent/prompts', 'prompts')
    ],
    hiddenimports=[
        'fastapi',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'starlette',
        'starlette.routing',
        'starlette.middleware',
        'starlette.middleware.cors',
        'anyio',
        'anyio._backends',
        'anyio._backends._asyncio',
        'langchain',
        'langchain_core',
        'langchain_google_genai',
        'langchain.agents',
        'langchain.tools',
        'langchain.memory',
        'langchain.prompts',
        'langchain.schema',
        'google.oauth2',
        'google.oauth2.credentials',
        'google.auth',
        'google.auth.transport',
        'google.auth.transport.requests',
        'googleapiclient',
        'googleapiclient.discovery',
        'pydantic',
        'pydantic_core',
        'httpx',
        'httpcore',
        'h11',
        'websockets',
        'certifi',
        'charset_normalizer',
        'idna',
        'sniffio',
        'mcp',
        'agent',
        'agent.agents',
        'agent.agents.agent',
        'agent.agents.google_agent',
        'agent.tools',
        'agent.services',
        'agent.services.google_service',
        'agent.models',
        'agent.models.mcp_config',
        'agent.settings',
        'agent.settings.settings'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy.tests',
        'scipy',
        'cv2',
        'torch',
        'tensorflow',
        'keras',
        'chromadb',
        'sentence_transformers',
        'hnswlib'
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)


exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Rong-E_agent',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Rong-E_agent',
)
